### ISSUE TITLE
Single spa react not loading in IE11

### ISSUE THREAD

**Issue by HarithaKR** [single-spa/single-spa-react#109]
Getting some error in IE when I try loading the single spa app. 
Unable to locate the error. as its not even breaking at the lifecycle methods. 
added promise polyfill. Then promise error was removed. But then also not loading in IE11

Pls help getting the single spa loading in IE. Its a react application
![image](https://user-images.githubusercontent.com/23190851/116542216-085cd200-a90a-11eb-866d-76affb9750e7.png)

**Comment by joeldenning** [comment]
Here's a code sandbox that shows single-spa-react working in IE11.

https://codesandbox.io/s/prod-framework-ror7c?file=/index.html

You need to polyfill both Promise and fetch for SystemJS, single-spa, and single-spa-react to work. If you're still seeing errors after that, then it's likely a problem with your code or one of the other dependencies.

**Comment by HarithaKR** [comment]
In this example, there is no importing of another application to this. Can you show an example of importing a react application to this application? Both react and that works in IE11?

**Comment by joeldenning** [comment]
No I can't create examples on demand for you. As the person reporting the issue, it's your job to prove that there's a problem. So could you please provide a demonstration of the issue?

**Comment by HarithaKR** [comment]
It was because of some local security setting in internet explorer. It was working fine in prod environment. 
Following the below steps helped it to work find in IE 11 local.
https://social.technet.microsoft.com/Forums/en-US/04f9da4a-fdf2-4cae-aaec-9f74335ff27c/how-to-get-ride-of-this-error-on-ie-11-browser-securityerror-failed-to-connect-to-websocket?forum=ieitprocurrentver

**Comment by HarithaKR** [comment]
However the demo apps given in the documentation are not working in IE. For the users reference, it would be helpful if those examples are working in IE11 as well. 
@joeldenning you need not create a new demo application and I didn't demand for it.

**Comment by joeldenning** [comment]
> However the demo apps given in the documentation are not working in IE.

The demo apps in the documentation do not work in IE11 because those who use it are software developers, who generally do not use IE11. I disagree that all the examples should work in IE11.

> @joeldenning you need not create a new demo application and I didn't demand for it.

I didn't say you demanded an example - I said you asked for it on-demand. See https://dictionary.cambridge.org/us/dictionary/english/on-demand, which explains that on-demand means on-request. You did request an example. Trying to claim otherwise is false and I do not appreciate you talking back to me about it. You are receiving free help from an open source maintainer, including a first example that I gave you. You provided zero demonstration of the issue and nothing useful to help debug it. You are lucky that you received a response within 24 hours and should not be upset when I instruct you on how it's your responsibility to provide a demonstration of the issue.
