### ISSUE TITLE
React 19 support?

### ISSUE THREAD

**Issue by SergioTx** [single-spa/single-spa-react#215]
Hello

React 19 released last week. How is the React 19 support? has anyone made it work with the latest version of React?

I tried updating an empty project to React 19 but when I try to replace it I get an error: `application '...' died in status LOADING_SOURCE_CODE: Cannot read properties of undefined (reading 'S')`.

That S is inside ReactSharedInternals from ReactDOM:

![image](https://github.com/user-attachments/assets/40d2c6fa-ad22-44ae-b407-f4bbb3901681)

The usage:

```js
const lifeCycles = singleSpaReact({
  React,
  ReactDOMClient,
  renderType: 'createRoot',
  rootComponent: AppView,
  errorBoundary(err, info, props) {
    return <></>;
  },
  domElementGetter: () => {
    return document.getElementById('content')!;
  },
});

export const { bootstrap, mount, unmount } = lifeCycles;
```

Any ideas?

**Comment by joeldenning** [comment]
React 19 works with the react-microfrontends examples. See https://react.microfrontends.app, https://github.com/react-microfrontends/shared-dependencies/pull/18/files, and https://github.com/react-microfrontends/navbar/blob/a1ce938516ac6f7c0a78dfb53242b5d2d6d49354/src/react-mf-navbar.js#L8

Closing since no way to demonstrate the issue. Feel free to reopen with repo / sandbox showing the issue
