### ISSUE TITLE
Add FunctionalComponent<any, any> in rootComponent @types for TypeScript

### ISSUE THREAD

**Issue by vadym-kukhtin** [single-spa/single-spa-react#50]
Please add FunctionalComponent<any, any> in rootComponent @types for TypeScript, because in modern React Development ClassicComponent typings are not really useful because everything can be implemented using hooks and functional components

**Comment by frehner** [comment]
Can you clarify what you mean? Currently this project doesn’t have any typings so are you asking to add typings to the project?

**Comment by joeldenning** [comment]
Not sure if I understand what you're proposing -- are you asking us to switching to function components + hooks?

Making the switch from class components to function components + hooks would be a breaking change for single-spa-react, since it requires react@16.8.0 and currently single-spa-react does not require react@16.8. I like hooks a lot, but would only want to rewrite our components if there's a real benefit beyond just our excitement for a new technology.

**Comment by mrmckeb** [comment]
Hi there, I believe the author is referring to this. 
![Screen Shot 2019-05-30 at 10 09 34](https://user-images.githubusercontent.com/5043083/58615163-0e337e00-82c3-11e9-9fd9-a3dc0c97fbc8.png)

Does this mean that `single-spa-react` won't work well with a functional component? Or is this just a mistake?

**Comment by frehner** [comment]
I’m not incredibly familiar with typings; they’re usually committed as a file with the source code aren’t they? We haven’t done that yet for single spa react but we’re not opposed to adding them. Just haven’t gotten to it. 

As far as what I think is happening here — single spa react does a simple check to see if your root / base component has a “componentDidCatch” lifecycle method on it. Functional components do not yet have a way of implementing error boundaries so we currently just warn you that you’ll probably want to wrap your app with a class component that does have an error boundary. 

The reason is that, in a microservice world, you want to be able to better handle different apps doing down without affecting other apps. An error boundary is a good way of doing that and giving a good UI for it.

**Comment by joeldenning** [comment]
Ah it looks like @sandersn created [@types/single-spa-react](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/single-spa-react).

I did not know that that had been done, and think I'd even prefer having the types right inside of this single-spa-react repo instead.

Looks like [this line of code](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/single-spa-react/index.d.ts#L20) is the one that is forcing it to be a class component instead of function components.

Since class components are the only way to implement [componentDidCatch](https://reactjs.org/docs/react-component.html#componentdidcatch), and since [single-spa-react warns by default if you don't implement componentDidCatch](https://github.com/CanopyTax/single-spa-react/blob/master/src/single-spa-react.js#L77-L83), it is encouraged to pass in a class component as the rootComponent.

However, it should still be possible to pass in a function component if they are [suppressing that warning](https://github.com/CanopyTax/single-spa-react/blob/master/src/single-spa-react.js#L77) or are just willing to live with the warning.

Fix for this would be to either modify [this file](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/single-spa-react) or to bring the types right into single-spa-react.

**Comment by sandersn** [comment]
Here are the authors of @types/single-spa-react: @Garrett-Smith-iq @chrisdopuch.

I'm the maintainer of Definitely Typed, which is why my name shows up on a lot of files there.
The advice from the Typescript team is to use Definitely Typed if you write your package in Javascript and don't want to maintain types. If you do want to maintain the types, still consider shipping with Definitely Typed if you want some oversight from the TS team. We are easier to get hold of there and test DT with the nightly build of TS.

**Comment by frehner** [comment]
Good to know, thanks for the info @sandersn . 

Guess the question is: do we want to have the typings in DT or do we want to maintain them here in the repo?  I'm not really seeing a disadvantage of having them in DT at the moment, and we can just PR that to update the typings. Thoughts?

**Comment by joeldenning** [comment]
I'm fine with keeping it in DefinitelyTyped -- the disadvantage is me not being able to get notifications for PRs to single-spa-react types without subscribing to all of DefinitelyTyped notifications. Also, it's just easier to forget that we have types and not update them if they're not in the same repo.

**Comment by sandersn** [comment]
@joeldenning For PRs, Typescript-bot tags people listed as typings authors so you’d just need to make sure you were on that list for single-spa-react.

**Comment by vadym-kukhtin** [comment]
@joeldenning Hey, sorry, was a bit busy! Yes, you got it correctly the main idea was to be able to add Functional Component as root, because typings were forcing to use only ComponentClass, but I got your answer. Anyway, thanks to everyone for participating and answering my question :) As I see it triggered a couple of valuable conversations

**Comment by joeldenning** [comment]
Awesome, PRs accepted to change this. Like [I described above](https://github.com/CanopyTax/single-spa-react/issues/50#issuecomment-497745301), functional components + hooks actually cannot implement any equivalent of Error Boundaries and componentDidCatch. And single-spa-react warns when you do this because it's good practice to have an error boundary for all React render trees.

All of that said, for people want to not implement an error boundary for their rootComponent, they should. So we should PR https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/single-spa-react to allow for it.

**Comment by joeldenning** [comment]
All types are now included in the `single-spa-react` package as of v4. See https://github.com/single-spa/single-spa-react/releases/tag/v4.0.0
