### ISSUE TITLE
Support for Nullable wrapwith or classname

### ISSUE THREAD

**Issue by BartJanvanAssen** [single-spa/single-spa-react#88]
Hey @joeldenning,

We have a use case where we want the parcel to not render an element but leave that responsibility to the parcel code itself. 
Would there be an option to not render an element but for example a fragment? 
I found this blog post about it: https://stackoverflow.com/questions/1776481/how-to-append-dom-element-into-an-empty-element-in-javascript

or maybe a second option would be, but to our use-case less preferable, to add a className option to the parcel element.

Little context: In our setup we requirre a strict css selector like: "document.body > class-name". Right now that is not possible with parcels and we always will have:

```
<body>
    <div> <!-- parcel div -->
        <div class='class-name'>{...}</div> <!-- parcel implementation div -->
    </div> <!-- parcel div -->
</body>
```

This would be the desired outcome:
```

<body>
        <div class='class-name'>{...}</div> <!-- parcel implementation div -->
</body>

```

I would be happy to help out if you can provide any feedback.

Regards,
Bart Jan

**Comment by joeldenning** [comment]
Single-spa requires a `domElement` for a parcel to render into, since frameworks including react require a container element when they are rendering into the dom element. This also helps frameworks not get confused by examining the same dom element for internal properties (which frameworks often do).

I recommend using raw react components wherever possible instead of parcels, since they do not have this issue.

Closing this issue since this is a known, documented part of single-spa parcels.

**Comment by BartJanvanAssen** [comment]
So it get it about the document element that needs to be created. But also my question was.. if wrapStyle and wrapWith are options why not wrapClassname or wrapId?

**Comment by joeldenning** [comment]
You did not mention wrapClassName or wrapId in your original post. I am open to adding props for className/id to the wrapper div.

**Comment by joeldenning** [comment]
To give more context on this - React always *_appends*_ to the container element that you provide via `ReactDOM.render(<Thing />, containerElement)` - it does not replace that element. Additionally, it first empties out the entire contents of containerElement before rendering. For this reason, you can't call `ReactDOM.render()` without having that intermediate div. Note that React does support rendering into a comment node instead of an HTMLElement (which solves the issues), but that support for that will probably be dropped in the next year or so. Even if we did rely on that for React parcels, it would not be viable since other frameworks do not support that feature and single-spa parcels must work regardless of which framework is implementing them.
