### ISSUE TITLE
Issue importing single-spa-react@latest into clean CRA project 

### ISSUE THREAD

**Issue by alanquigley-toast** [single-spa/single-spa-react#93]
This fails
`import Parcel from 'single-spa-react/parcel';`

This works
`import Parcel from 'single-spa-react/lib/esm/parcel';`

**Comment by joeldenning** [comment]
This is due to webpack@<5.0.0-beta.18 not properly supporting the package.json `exports` field yet. See related:

- https://github.com/single-spa/single-spa-react/blob/c38dd22b1fc36e57d5cff75e0769df187764ef7a/package.json#L13
- https://github.com/single-spa/single-spa-react/releases/tag/v3.0.0

CRA uses webpack 4 which is why this is the case. The release notes I linked to show the options for this.

**Comment by alanquigley-toast** [comment]
Thanks!

**Comment by raphaelsantos-hotmart** [comment]
Hello, I'm trying to use Parcel in version 3.1.0, when importing using "single-spa-react/parcel" I'm getting this error:

```
ERROR in ./node_modules/single-spa-react/lib/esm/parcel.js
Can't import the named export 'SingleSpaContext'. 'Consumer'
```

I'm using node v.15.0.1, npm 7.0.3 and webpack 5.3.2
@joeldenning is there any configuration missing?

**Comment by joeldenning** [comment]
Hi @raphaelsantos-hotmart, I tried this out just now and was able to get single-spa-react working with webpack 5. Here's my code: https://github.com/joeldenning/single-spa-react-test. This code is not a recommendation of how to set up a project - it was me debugging.

Could you provide a demonstration of the issue?

**Comment by raphaelsantos-hotmart** [comment]
Perfect @joeldenning, thank you very much for the quick help, your code worked well, i will try to find the problem on my side, if i find the problem i will come back here to tell you, thanks again.
